[2025-03-02T21:10:39.203+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T21:10:39.233+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_entities.extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes manual__2025-03-02T21:10:13.514914+00:00 [queued]>
[2025-03-02T21:10:39.250+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_entities.extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes manual__2025-03-02T21:10:13.514914+00:00 [queued]>
[2025-03-02T21:10:39.252+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-02T21:10:39.273+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes> on 2025-03-02 21:10:13.514914+00:00
[2025-03-02T21:10:39.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T21:10:39.284+0000] {standard_task_runner.py:72} INFO - Started process 130 to run task
[2025-03-02T21:10:39.284+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'execute_entities', 'extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes', 'manual__2025-03-02T21:10:13.514914+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/execute_entities.py', '--cfg-path', '/tmp/tmpyzxsl7c2']
[2025-03-02T21:10:39.286+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes
[2025-03-02T21:10:39.355+0000] {task_command.py:467} INFO - Running <TaskInstance: execute_entities.extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes manual__2025-03-02T21:10:13.514914+00:00 [running]> on host eba33f90d1de
[2025-03-02T21:10:39.506+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_entities' AIRFLOW_CTX_TASK_ID='extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T21:10:13.514914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T21:10:13.514914+00:00'
[2025-03-02T21:10:39.509+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T21:10:42.040+0000] {log.py:232} WARNING - 2025-03-02 21:10:42.039 | INFO     | src.controllers.paginations.paginations:per_page:91 - Page 1 fetched. Total of records: 5
[2025-03-02T21:10:44.184+0000] {log.py:232} WARNING - 2025-03-02 21:10:44.184 | ERROR    | src.db.database:save_into_db:110 - Error saving data into table contacorrente: Using URI string without sqlalchemy installed.
[2025-03-02T21:10:44.185+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T21:10:44.198+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T21:10:44.199+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=execute_entities, task_id=extract_and_load_omie_entities.extract_and_load_ListarContasCorrentes, run_id=manual__2025-03-02T21:10:13.514914+00:00, execution_date=20250302T211013, start_date=20250302T211039, end_date=20250302T211044
[2025-03-02T21:10:44.248+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T21:10:44.261+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-02T21:10:44.286+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
