[2025-03-02T21:11:02.068+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T21:11:02.099+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_entities.extract_and_load_omie_second_flow.extract_and_load_ListarExtrato manual__2025-03-02T21:10:13.514914+00:00 [queued]>
[2025-03-02T21:11:02.120+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_entities.extract_and_load_omie_second_flow.extract_and_load_ListarExtrato manual__2025-03-02T21:10:13.514914+00:00 [queued]>
[2025-03-02T21:11:02.121+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-02T21:11:02.144+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_omie_second_flow.extract_and_load_ListarExtrato> on 2025-03-02 21:10:13.514914+00:00
[2025-03-02T21:11:02.159+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'execute_entities', 'extract_and_load_omie_second_flow.extract_and_load_ListarExtrato', 'manual__2025-03-02T21:10:13.514914+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/execute_entities.py', '--cfg-path', '/tmp/tmp4f6l8_4y']
[2025-03-02T21:11:02.157+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=133) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T21:11:02.164+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask extract_and_load_omie_second_flow.extract_and_load_ListarExtrato
[2025-03-02T21:11:02.164+0000] {standard_task_runner.py:72} INFO - Started process 134 to run task
[2025-03-02T21:11:02.256+0000] {task_command.py:467} INFO - Running <TaskInstance: execute_entities.extract_and_load_omie_second_flow.extract_and_load_ListarExtrato manual__2025-03-02T21:10:13.514914+00:00 [running]> on host eba33f90d1de
[2025-03-02T21:11:02.388+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='execute_entities' AIRFLOW_CTX_TASK_ID='extract_and_load_omie_second_flow.extract_and_load_ListarExtrato' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T21:10:13.514914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T21:10:13.514914+00:00'
[2025-03-02T21:11:02.390+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T21:11:03.796+0000] {log.py:232} WARNING - 2025-03-02 21:11:03.795 | ERROR    | unusual_prefix_e1fa9472b12de8b81df92a96de8ef1a678e0bb08_execute_entities:get_cutomers:76 - An error occurred while pagination: 'PaginationController' object has no attribute 'data_range'
[2025-03-02T21:11:03.797+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T21:11:03.814+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T21:11:03.815+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=execute_entities, task_id=extract_and_load_omie_second_flow.extract_and_load_ListarExtrato, run_id=manual__2025-03-02T21:10:13.514914+00:00, execution_date=20250302T211013, start_date=20250302T211102, end_date=20250302T211103
[2025-03-02T21:11:03.871+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T21:11:03.912+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T21:11:03.916+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
